/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 27-May-2022 10:45:32 AM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `accounts` CASCADE
;

DROP TABLE IF EXISTS `accounts_m2m_statuses` CASCADE
;

DROP TABLE IF EXISTS `offices` CASCADE
;

DROP TABLE IF EXISTS `owners` CASCADE
;

DROP TABLE IF EXISTS `payments_archive` CASCADE
;

DROP TABLE IF EXISTS `payments_operational` CASCADE
;

DROP TABLE IF EXISTS `site_pages` CASCADE
;

DROP TABLE IF EXISTS `statuses` CASCADE
;

/* Create Tables */

CREATE TABLE `accounts`
(
	`a_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`a_owner` BIGINT UNSIGNED NOT NULL,
	`a_is_system` BOOL NOT NULL,
	`a_balance` DECIMAL(19,4) NOT NULL,
	CONSTRAINT `PK_accounts` PRIMARY KEY (`a_id` ASC)
)

;

CREATE TABLE `accounts_m2m_statuses`
(
	`ams_a_id` BIGINT UNSIGNED NOT NULL,
	`ams_s_id` TINYINT UNSIGNED NOT NULL,
	`ams_last_update` DATETIME NOT NULL,
	CONSTRAINT `PK_accounts_m2m_statuses` PRIMARY KEY (`ams_a_id` ASC, `ams_s_id` ASC)
)

;

CREATE TABLE `offices`
(
	`of_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`of_city` VARCHAR(50) NULL,
	`of_name` VARCHAR(50) NULL,
	`of_sales` INT NULL,
	`of_page` SMALLINT UNSIGNED NULL,
	CONSTRAINT `PK_offices` PRIMARY KEY (`of_id` ASC)
)

;

CREATE TABLE `owners`
(
	`o_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`o_name` VARCHAR(200) NOT NULL,
	`o_office` TINYINT UNSIGNED NOT NULL,
	CONSTRAINT `PK_owners` PRIMARY KEY (`o_id` ASC)
)

;

CREATE TABLE `payments_archive`
(
	`pa_id` BIGINT UNSIGNED NOT NULL,
	`pa_from` BIGINT UNSIGNED NOT NULL,
	`pa_to` BIGINT UNSIGNED NOT NULL,
	`pa_money` DECIMAL(19,4) NULL,
	`pa_dt` DATETIME NOT NULL,
	CONSTRAINT `PK_payments_archive` PRIMARY KEY (`pa_id` ASC)
)

;

CREATE TABLE `payments_operational`
(
	`po_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`po_from` BIGINT UNSIGNED NOT NULL,
	`po_to` BIGINT UNSIGNED NOT NULL,
	`po_money` DECIMAL(19,4) NULL,
	`po_dt` DATETIME NOT NULL,
	CONSTRAINT `PK_payments_operational` PRIMARY KEY (`po_id` ASC)
)

;

CREATE TABLE `site_pages`
(
	`sp_id` SMALLINT UNSIGNED NOT NULL,
	`sp_parent` SMALLINT UNSIGNED NULL,
	`sp_name` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_site_pages` PRIMARY KEY (`sp_id` ASC)
)

;

CREATE TABLE `statuses`
(
	`s_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`s_name` VARCHAR(200) NOT NULL,
	CONSTRAINT `PK_statuses` PRIMARY KEY (`s_id` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `offices` 
 ADD INDEX `idx_city` (`of_city` ASC)
;

ALTER TABLE `owners` 
 ADD INDEX `idx_o_name` (`o_name` ASC)
;

ALTER TABLE `statuses` 
 ADD INDEX `idx_s_name` (`s_name` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `accounts` 
 ADD CONSTRAINT `FK_accounts_owners`
	FOREIGN KEY (`a_owner`) REFERENCES `owners` (`o_id`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `accounts_m2m_statuses` 
 ADD CONSTRAINT `FK_accounts_m2m_statuses_accounts`
	FOREIGN KEY (`ams_a_id`) REFERENCES `accounts` (`a_id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `accounts_m2m_statuses` 
 ADD CONSTRAINT `FK_accounts_m2m_statuses_statuses`
	FOREIGN KEY (`ams_s_id`) REFERENCES `statuses` (`s_id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `offices` 
 ADD CONSTRAINT `FK_offices_site_pages`
	FOREIGN KEY (`of_page`) REFERENCES `site_pages` (`sp_id`) ON DELETE Set Null ON UPDATE Cascade
;

ALTER TABLE `owners` 
 ADD CONSTRAINT `FK_owners_offices`
	FOREIGN KEY (`o_office`) REFERENCES `offices` (`of_id`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `payments_archive` 
 ADD CONSTRAINT `FK_payments_archive_accounts_from`
	FOREIGN KEY (`pa_from`) REFERENCES `accounts` (`a_id`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `payments_archive` 
 ADD CONSTRAINT `FK_payments_archive_accounts_to`
	FOREIGN KEY (`pa_to`) REFERENCES `accounts` (`a_id`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `payments_operational` 
 ADD CONSTRAINT `FK_payments_operational_accounts_from`
	FOREIGN KEY (`po_from`) REFERENCES `accounts` (`a_id`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `payments_operational` 
 ADD CONSTRAINT `FK_payments_operational_accounts_to`
	FOREIGN KEY (`po_to`) REFERENCES `accounts` (`a_id`) ON DELETE Restrict ON UPDATE Cascade
;

ALTER TABLE `site_pages` 
 ADD CONSTRAINT `FK_site_pages_site_pages`
	FOREIGN KEY (`sp_parent`) REFERENCES `site_pages` (`sp_id`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1
; 
